const fakeBlogData = [
  {
    "id": 1,
    "category": "Body",
    "title": "Dealing with pain during postpartum",
    "isRecommended": true,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "6th October 2025",
    "content":
        "The postpartum period, which follows childbirth, is a time of physical healing and adjustment for mothers. Experiencing pain is common and can vary in intensity depending on the type of delivery and individual recovery. Understanding and managing postpartum pain is crucial for comfort, mobility, and overall well-being. One of the most common postpartum pains is perineal pain, especially after vaginal delivery. This area, which may have experienced tears or an episiotomy, can feel sore and sensitive. Applying ice packs, using sitz baths, and taking prescribed pain relievers can help alleviate discomfort.",
  },
  {
    "id": 2,
    "category": "Body",
    "title": "Pelvic Floor Health and Incontinence",
    "isRecommended": true,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "Pelvic Specialist",
    "date": "6th June 2025",
    "content":
        "In this video, Dr. Vaneem explains how the pelvic floor muscles are affected by pregnancy and birth. We cover gentle exercises to regain bladder control and strengthen the core safely during the first six weeks of recovery.",
  },
  {
    "id": 3,
    "category": "Self-care",
    "title": "Finding Small Moments for Yourself",
    "isRecommended": true,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Sarah Jenkins",
    "occupation": "Postpartum Coach",
    "date": "10th October 2025",
    "content":
        "Self-care after a baby isn't about long spa days; it's about the 5-minute windows. Whether it's a hot cup of tea or a short breathing exercise, reclaiming small moments of your day is vital for your mental resilience.",
  },
  {
    "id": 4,
    "category": "Mind and mood",
    "title": "Understanding Baby Blues vs. PPD",
    "isRecommended": false,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Dr. Elena Rossi",
    "occupation": "Psychologist",
    "date": "12th October 2025",
    "content":
        "It's normal to feel emotional after birth, but knowing the difference between the 'baby blues' and Postpartum Depression (PPD) is key. We discuss the symptoms to watch for and when it's time to reach out for professional support.",
  },
  {
    "id": 5,
    "category": "Cultural care",
    "title": "Traditional Healing Practices",
    "isRecommended": false,
    "duration": "4mins",
    "type": "article",
    "authorsName": "Amara Okafor",
    "occupation": "Doula",
    "date": "14th October 2025",
    "content":
        "Exploring cultural traditions from around the world that prioritize the 'sitting month' or specialized nutrition for new mothers to help the body recover through ancestral wisdom.",
  },
  {
    "id": 6,
    "category": "Baby care",
    "title": "Mastering the Newborn Swaddle",
    "isRecommended": true,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "15th October 2025",
    "content":
        "A step-by-step video guide on how to swaddle your baby safely to promote better sleep while ensuring hip health and temperature regulation.",
  },
  {
    "id": 7,
    "category": "Body",
    "title": "Gentle Movement: Starting Safely",
    "isRecommended": false,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "16th October 2025",
    "content":
        "Movement is medicine, but timing is everything. This video demonstrates low-impact movements you can start doing at home to increase circulation without straining your recovery.",
  },
  {
    "id": 8,
    "category": "Mind and mood",
    "title": "The Power of Positive Affirmations",
    "isRecommended": false,
    "duration": "1min",
    "type": "article",
    "authorsName": "Sarah Jenkins",
    "occupation": "Postpartum Coach",
    "date": "17th October 2025",
    "content":
        "Your thoughts shape your reality. We’ve curated 10 powerful affirmations for new mothers to help combat feelings of inadequacy and embrace the learning curve of parenthood.",
  },
  {
    "id": 9,
    "category": "Self-care",
    "title": "Nutrition for Postpartum Healing",
    "isRecommended": true,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "Nutritionist",
    "date": "18th October 2025",
    "content":
        "What you eat affects how you heal. Learn about the 'superfoods' that support tissue repair, boost energy levels, and provide the nutrients needed for breastfeeding mothers.",
  },
  {
    "id": 10,
    "category": "Cultural care",
    "title": "Postpartum Massage Traditions",
    "isRecommended": false,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Amara Okafor",
    "occupation": "Doula",
    "date": "19th October 2025",
    "content":
        "From Jamu massage in Indonesia to Ayurvedic oil treatments, we look at how different cultures use touch and massage to help the uterus contract and reduce swelling.",
  },
  {
    "id": 11,
    "category": "Baby care",
    "title": "Understanding Newborn Sleep Cycles",
    "isRecommended": true,
    "duration": "5mins",
    "type": "article",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "20th October 2025",
    "content":
        "Newborns don't sleep like adults. Understanding their short sleep cycles and 'active sleep' phases can help parents feel less frustrated during those midnight wake-ups.",
  },
  {
    "id": 12,
    "category": "Body",
    "title": "C-Section Recovery 101",
    "isRecommended": false,
    "duration": "4mins",
    "type": "article",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "21st October 2025",
    "content":
        "A specialized guide for mothers recovering from abdominal surgery. We discuss scar care, pain management, and how to lift your baby without hurting your incision.",
  },
  {
    "id": 13,
    "category": "Mind and mood",
    "title": "Managing Intimacy After Birth",
    "isRecommended": false,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Dr. Elena Rossi",
    "occupation": "Psychologist",
    "date": "22st October 2025",
    "content":
        "Returning to intimacy is a journey, not a destination. We talk about communication with your partner, physical readiness, and the emotional shifts that happen after birth.",
  },
  {
    "id": 14,
    "category": "Self-care",
    "title": "Hydration and Hair Health",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "General Practitioner",
    "date": "23rd October 2025",
    "content":
        "Postpartum hair loss can be startling. Learn why it happens and how staying hydrated and taking specific vitamins can help support your body through hormonal shifts.",
  },
  {
    "id": 15,
    "category": "Baby care",
    "title": "Soothing a Colicky Baby",
    "isRecommended": true,
    "duration": "4mins",
    "type": "video",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "24th October 2025",
    "content":
        "In this video, we demonstrate the '5 S's' technique to calm a crying infant and provide tips for parents on staying calm when baby won't stop crying.",
  },
  {
    "id": 16,
    "category": "Cultural care",
    "title": "The Role of the Village",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Amara Okafor",
    "occupation": "Doula",
    "date": "25th October 2025",
    "content":
        "Western society often prioritizes independence, but most cultures believe it takes a village. We explore how to build your own support system even if family lives far away.",
  },
  {
    "id": 17,
    "category": "Body",
    "title": "Breastfeeding and Back Pain",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "26th October 2025",
    "content":
        "Poor posture during feeding can lead to chronic neck and back pain. We show you the best ergonomic positions and pillow setups to keep you comfortable while feeding.",
  },
  {
    "id": 18,
    "category": "Mind and mood",
    "title": "Processing Your Birth Story",
    "isRecommended": true,
    "duration": "4mins",
    "type": "article",
    "authorsName": "Dr. Elena Rossi",
    "occupation": "Psychologist",
    "date": "27th October 2025",
    "content":
        "Whether your birth went to plan or took a turn, writing down your story can be a therapeutic way to process the experience and celebrate your strength.",
  },
  {
    "id": 19,
    "category": "Self-care",
    "title": "Better Sleep for New Moms",
    "isRecommended": true,
    "duration": "3mins",
    "type": "video",
    "authorsName": "Sarah Jenkins",
    "occupation": "Postpartum Coach",
    "date": "28th October 2025",
    "content":
        "Sleep is a luxury, but quality matters over quantity. This video gives you tips on 'sleep hygiene' to help you fall back asleep faster after those middle-of-the-night feedings.",
  },
  {
    "id": 20,
    "category": "Baby care",
    "title": "Diaper Rash: Prevention and Cure",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "29th October 2025",
    "content":
        "A quick guide on identifying different types of diaper rash and the best practices for keeping your baby's skin dry and healthy.",
  },
];
