const fakeBlogData = [
  {
    "id": 1,
    "category": "Body & Recovery",
    "title": "Pelvic Floor Health and Incontinence",
    "isRecommended": false,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "Pelvic Specialist",
    "date": "6th June 2025",
    "content": "In the early stages of learning how to build software...",
    "image": "assets/images/girl-down-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 2,
    "category": "Self-care",
    "title": "Finding Small Moments for Yourself",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Sarah Jenkins",
    "occupation": "Postpartum Coach",
    "date": "10th October 2025",
    "content": "Self-care after a baby isn't about long spa days...",
    "image": "assets/images/happy-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 3,
    "category": "Mind and mood",
    "title": "Dealing with pain during postpartum",
    "isRecommended": true,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "6th October 2025",
    "content":
        "Pelvic floor health is a crucial but often overlooked part of postpartum recovery. The pelvic floor is a group of muscles that support the bladder, uterus, and bowel, and pregnancy places significant strain on them. After childbirth, these muscles may become weakened, leading to issues such as urinary incontinence, discomfort, or a feeling of heaviness. These symptoms are common, but they are not something you simply have to live with. Understanding what your body is experiencing is the first step toward healing.\n\nGentle pelvic floor exercises, often referred to as Kegels, can help rebuild strength and improve muscle control. However, timing and technique matter. Doing exercises incorrectly or too early can sometimes worsen symptoms. This is why guided recovery, either through a pelvic health specialist or structured programs, can make a huge difference.\n\nIt’s also important to recognize that recovery is not linear. Some days will feel better than others, and that’s completely normal. With patience, consistency, and proper support, most women experience significant improvement. Prioritizing pelvic floor health is not just about recovery—it’s about long-term comfort, confidence, and quality of life.",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 4,
    "category": "Mind and mood",
    "title": "Understanding Baby Blues vs. PPD",
    "isRecommended": false,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Dr. Elena Rossi",
    "occupation": "Psychologist",
    "date": "12th October 2025",
    "content": "It's normal to feel emotional after birth...",
    "image": "assets/images/sad-girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 5,
    "category": "Cultural care",
    "title": "Traditional Healing Practices",
    "isRecommended": false,
    "duration": "4mins",
    "type": "article",
    "authorsName": "Amara Okafor",
    "occupation": "Doula",
    "date": "14th October 2025",
    "content": "Exploring cultural traditions from around the world...",
    "image": "assets/images/girl-laugh-removebg.png",
    "picture": " 'assets/images/doctor-lady.jpeg",
  },
  {
    "id": 6,
    "category": "Baby care",
    "title": "Mastering the Newborn Swaddle",
    "isRecommended": true,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "15th October 2025",
    "content": "A step-by-step video guide on how to swaddle...",
    "image": "assets/images/happy-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 7,
    "category": "Body & Recovery",
    "title": "Gentle Movement: Starting Safely",
    "isRecommended": false,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "16th October 2025",
    "content": "Movement is medicine, but timing is everything...",
    "image": "assets/images/girl-laugh-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 8,
    "category": "Mind and mood",
    "title": "The Power of Positive Affirmations",
    "isRecommended": false,
    "duration": "1min",
    "type": "article",
    "authorsName": "Sarah Jenkins",
    "occupation": "Postpartum Coach",
    "date": "17th October 2025",
    "content": "Your thoughts shape your reality...",
    "image": "assets/images/girl-bluff-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg,",
  },
  {
    "id": 9,
    "category": "Self-care",
    "title": "Nutrition for Postpartum Healing",
    "isRecommended": true,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "Nutritionist",
    "date": "18th October 2025",
    "content": "What you eat affects how you heal...",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 10,
    "category": "Cultural care",
    "title": "Postpartum Massage Traditions",
    "isRecommended": false,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Amara Okafor",
    "occupation": "Doula",
    "date": "19th October 2025",
    "content": "From Jamu massage in Indonesia...",
    "image": "assets/images/happy-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 11,
    "category": "Baby care",
    "title": "Understanding Newborn Sleep Cycles",
    "isRecommended": true,
    "duration": "5mins",
    "type": "article",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "20th October 2025",
    "content": "Newborns don't sleep like adults...",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 12,
    "category": "Body & Recovery",
    "title": "C-Section Recovery 101",
    "isRecommended": false,
    "duration": "4mins",
    "type": "article",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "21st October 2025",
    "content": "A specialized guide for mothers...",
    "image": "assets/images/happy-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 13,
    "category": "Mind and mood",
    "title": "Managing Intimacy After Birth",
    "isRecommended": false,
    "duration": "3mins",
    "type": "article",
    "authorsName": "Dr. Elena Rossi",
    "occupation": "Psychologist",
    "date": "22st October 2025",
    "content": "Returning to intimacy is a journey...",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 14,
    "category": "Self-care",
    "title": "Hydration and Hair Health",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "General Practitioner",
    "date": "23rd October 2025",
    "content": "Postpartum hair loss can be startling...",
    "image": "assets/images/girl-down-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 15,
    "category": "Baby care",
    "title": "Soothing a Colicky Baby",
    "isRecommended": true,
    "duration": "4mins",
    "type": "video",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "24th October 2025",
    "content": "In this video, we demonstrate the '5 S's'...",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 16,
    "category": "Cultural care",
    "title": "The Role of the Village",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Amara Okafor",
    "occupation": "Doula",
    "date": "25th October 2025",
    "content": "Western society often prioritizes independence...",
    "image": "assets/images/girl-bluff-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 17,
    "category": "Body & Recovery",
    "title": "Breastfeeding and Back Pain",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Dr. Precious Daniels",
    "occupation": "Physiotherapist",
    "date": "26th October 2025",
    "content": "Poor posture during feeding can lead to pain...",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 18,
    "category": "Mind and mood",
    "title": "Processing Your Birth Story",
    "isRecommended": true,
    "duration": "4mins",
    "type": "article",
    "authorsName": "Dr. Elena Rossi",
    "occupation": "Psychologist",
    "date": "27th October 2025",
    "content": "Whether your birth went to plan...",
    "image": "assets/images/girl-mean-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 19,
    "category": "Self-care",
    "title": "Better Sleep for New Moms",
    "isRecommended": true,
    "duration": "3mins",
    "type": "video",
    "authorsName": "Sarah Jenkins",
    "occupation": "Postpartum Coach",
    "date": "28th October 2025",
    "content": "Sleep is a luxury, but quality matters...",
    "image": "assets/images/girl-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 20,
    "category": "Baby care",
    "title": "Diaper Rash: Prevention and Cure",
    "isRecommended": false,
    "duration": "2mins",
    "type": "article",
    "authorsName": "Nurse Beth",
    "occupation": "Neonatal Nurse",
    "date": "29th October 2025",
    "content": "A quick guide on identifying diaper rash...",
    "image": "assets/images/girl-bluff-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
];
