final searchTopBlog = [
  {
    "id": 1,
    "category": "Top Blogs",
    "title": "Pelvic Floor Health and Incontinence",
    "duration": "2mins",
    "type": "video",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "Pelvic Specialist",
    "date": "6th June 2025",
    "content": "In the early stages of learning how to build software...",
    "image": "assets/images/girl-down-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
  {
    "id": 2,
    "category": "Top Blogs",
    "title": "Pelvic Floor Health and Incontinence",
    "isRecommended": false,
    "duration": "2mins",
    "type": "video",
    "authorsName": "Dr. Sledge Vaneem",
    "occupation": "Pelvic Specialist",
    "date": "6th June 2025",
    "content": "In the early stages of learning how to build software...",
    "image": "assets/images/girl-down-removebg.png",
    "picture": "assets/images/doctor-lady.jpeg",
  },
];
